
# Classes and Objects

Classes and objects is usually an advanced topic.  But we present it early because in the student product inventory project we need to create customer and sales order data.  As you will see, it is far easier to do this using objects that using dictionaries, which is how you would do it if classes did not exist.

Here is a diagram from our student project to create an inventory system.  As you can see a customer has a variable number of sales orders.  Think of when you (the customer) go to the store and buy something (the orders).  Every time you go back to buy something else you create another sales order.  But you only have one customer record since you are just you.   

![inventory system](https://github.com/werowe/HypatiaAcademy/blob/master/images/Python%20Student%20Project%20(1).jpg?raw=true)

If you were to use a dictionary you might represent a customer like this:

In [196]:
customer = { "customerNumber": 123,
            "name": "Walker", 
            "postalcode": 8035 }

And then you might present an order like this:

In [197]:
from datetime import date

order1 = { "customerNumber": 123,
          "orderNumber" : 456, 
         "orderdate": date.today().strftime('%Y-%h-%d'), 
         "productNumber": "EA123", 
         "quantity": 150 }

order2 = { "customerNumber": 123,
           "orderNumber" : 789, 
         "orderdate": date.today().strftime('%Y-%h-%d'), 
         "productNumber": "EA456", 
         "quantity": 300 }


You would then assign orders to the customer dictionary by making a new key called **orders** then adding the two dictioaries order1 and order 2 as values.

In [198]:
customer["orders"] = [order1,order2]

Then when you print it out, using the pretty printer (pprint) method it looks like this.

In [199]:
import pprint

pp = pprint.PrettyPrinter(indent=4)

pp.pprint(customer)

{   'customerNumber': 123,
    'name': 'Walker',
    'orders': [   {   'customerNumber': 123,
                      'orderNumber': 456,
                      'orderdate': '2020-Aug-29',
                      'productNumber': 'EA123',
                      'quantity': 150},
                  {   'customerNumber': 123,
                      'orderNumber': 789,
                      'orderdate': '2020-Aug-29',
                      'productNumber': 'EA456',
                      'quantity': 300}],
    'postalcode': 8035}


That's ok, but to refer to the order you would have to use the key **orders** and then the array index to print an order.  

In [200]:
customer["orders"][0]

{'customerNumber': 123,
 'orderNumber': 456,
 'orderdate': '2020-Aug-29',
 'productNumber': 'EA123',
 'quantity': 150}

That looks really odd when you want to get the order quanity for the first order:

In [201]:
customer["orders"][0]["quantity"]

150

A more natural way to do that is to use objects.

We use the word **class**.  Each class must have a **constructor**, which is the funcion that gives the object it's initial values.  The bare minimum we need to give a customer is the customerNumber. So we will put that in the constructor.

We use the word **self** to refer to the class.  So this line

`self.customerNumber=customerNumber`

means to assign to the Customer member element **customerNumber** the parameter **customerNumber** vaue, which is a parameter in the constructor function.

You should initialize all your variables in the constructor. So here we make an orders array to hold all our orders.  We set its inital value to [].

In [202]:
class Customer:
    
     
    def __init__(self,customerNumber):
        self.customerNumber=customerNumber
        self.orders = []
    
    def addOrder(self, order):
        self.orders.append(order)
        
    def getOrders(self):
        return self.orders
        
        

We then create a **customer** object by putting the class name **Customer** in parantheses.  In the paranthese we pass it the customerNumber.

In [203]:
cust=Customer(123)

Now we can see that we have created (The correct word is **instantiated**) a Customer class creating a Customer object.

The constructor `init()` ran giving the cust.customerNumber the value 123.  We can see that here.



In [204]:
print(cust.customerNumber)

123


We can create a new variable in the Customer object just by adding a name and value.  Like `cust.newField = someValue`.

(**Note**: You should note that writing a value to an object's attributes is **not** allowed in most other programming languages, like Java. Java requires you to write a function to do that.)

In [205]:
cust.customerName="Walker"
print(cust.customerName)

Walker


Now let's make a sales order class.  The constructor here will have lots of fields as we need more that customer a customer number.  We need order number, date product number, etc.

In [206]:
class Order:
    
    def __init__(self,customerNumber, orderNumber, orderDate,productNumber,quantity):
        self.customerNumber=customerNumber
        self.orderNumber = orderNumber
        self.orderDate = orderDate
        self.productNumber = productNumber
        self.quantity = quantity



Here is how you create orders.

In [207]:
ord1 = Order(123, 456, '2020-Aug-29', 'EA123', 150)
ord2 = Order(123, 789, '2020-Aug-29', 'EA456', 300)

Then you call the function `Customer.addOrder()` to add orders to the Customer.orders[] array.  We call that a **member** function since it is a member of the Customer class. In other words you cannot use this function outside the class.  It has become part of the Customer class. Its sole purpose is to add orders to Customer objects.

Here is that function:

```python
def addOrder(self, order):
        self.orders.append(order)
```
        

In [208]:
cust.addOrder(ord1)
cust.addOrder(ord2)

Since orders in an array, getOrders() is an array, so let's print them out by looping through the array.  Here is the getOrders function:

```python
 def getOrders(self):
        return self.orders
```        

In [209]:
for ord in cust.getOrders():
    print("Customer Number",ord.customerNumber, "Order Number=",ord.orderNumber)

Customer Number 123 Order Number= 456
Customer Number 123 Order Number= 789


# Inheritance

We won't need this for the inventory system but its important to understand the concept of **inheritance**.

Suppose we have the object **ball**.  Then we have another obect which is also a ball, but is a special type of ball.  Call it **basket ball**.

In Python if we create a BasketBall class it would not be necessary to add all the attributes that make a ball, like size, weight, material, etc.  We would just add what is unique to a basketball compared to other types of balls.

We say that a basketball **inherits** the problems of a regular ball.

Let's illustrate that with an example, suppose in our inventory system we have regular customers and we have VIP customers.  Those would be the same as regular customers except they have a customerStatus of **VIP**.

We would create the VipCustomer like this.  The only difference it the format:

```python
class NewClass (BaseClass):
```


In [210]:
class VipCustomer (Customer):
    
    customerStatus = "VIP"

So create a VIP Customer.  We give it the customerNumber **789** which is passed to the constructor of the Customer object.  Then we hard-code the status as `customerStatus="VIP"`.  We also could have written our own constructor to give the customer other attributes, like a special discount or perks.

In [211]:
vipCustomer = VipCustomer("789")

Now notice that the vipCustomer has both a customerStatus and customerNumber.

In [212]:
print(vipCustomer.customerStatus)
print(vipCustomer.customerNumber)

VIP
789
