<a href="https://colab.research.google.com/github/werowe/HypatiaAcademy/blob/master/class/2024_09_17_working_lecture_save_forecast_to_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
j={
    "city": {
        "coord": {
            "lat": 49.4413,
            "lon": 32.0643
        },
        "country": "UA",
        "id": 710791,
        "name": "Cherkasy",
        "population": 297568,
        "sunrise": 1726803333,
        "sunset": 1726847685,
        "timezone": 10800
    },
    "cnt": 40,
    "cod": "200",
    "list": [
        {
            "clouds": {
                "all": 8
            },
            "dt": 1726855200,
            "dt_txt": "2024-09-20 18:00:00",
            "main": {
                "feels_like": 20.82,
                "grnd_level": 1011,
                "humidity": 41,
                "pressure": 1022,
                "sea_level": 1022,
                "temp": 21.54,
                "temp_kf": 2.88,
                "temp_max": 21.54,
                "temp_min": 18.66
            },
            "pop": 0,
            "sys": {
                "pod": "n"
            },
            "visibility": 10000,
            "weather": [
                {
                    "description": "\u0447\u0438\u0441\u0442\u0435 \u043d\u0435\u0431\u043e",
                    "icon": "01n",
                    "id": 800,
                    "main": "Clear"
                }
            ],
            "wind": {
                "deg": 11,
                "gust": 2.96,
                "speed": 2.91
            }
        }]
}

In [65]:
# j is the dictionary

# j['list'] its the forecast weather for 7 * 8 appx 42

# jj['list'][0]. the first item in the list.


j['list'][0]['main'].keys()

dict_keys(['feels_like', 'grnd_level', 'humidity', 'pressure', 'sea_level', 'temp', 'temp_kf', 'temp_max', 'temp_min'])

In [66]:
# goal is to flatten list

j['list']

[{'clouds': {'all': 8},
  'dt': 1726855200,
  'dt_txt': '2024-09-20 18:00:00',
  'main': {'feels_like': 20.82,
   'grnd_level': 1011,
   'humidity': 41,
   'pressure': 1022,
   'sea_level': 1022,
   'temp': 21.54,
   'temp_kf': 2.88,
   'temp_max': 21.54,
   'temp_min': 18.66},
  'pop': 0,
  'sys': {'pod': 'n'},
  'visibility': 10000,
  'weather': [{'description': 'чисте небо',
    'icon': '01n',
    'id': 800,
    'main': 'Clear'}],
  'wind': {'deg': 11, 'gust': 2.96, 'speed': 2.91}}]

In [68]:

# place to put days
w=[]

l=dict()

# this means get the first item from the list, it will be a dictionary

g=j['list'][0]


# so only is we have a dictionary do this



# this means make a new dictionary with the items in g


  # add logic to do this step only if the value v is a dictionary

#HINT:  we only have 3 dictionaries in clouds, main, sys

for k, v in g.items():

  l[k]=v
  print(l)

# add each dictionary to the list

w.append(l)

#w





{'clouds': {'all': 8}}
{'clouds': {'all': 8}, 'dt': 1726855200}
{'clouds': {'all': 8}, 'dt': 1726855200, 'dt_txt': '2024-09-20 18:00:00'}
{'clouds': {'all': 8}, 'dt': 1726855200, 'dt_txt': '2024-09-20 18:00:00', 'main': {'feels_like': 20.82, 'grnd_level': 1011, 'humidity': 41, 'pressure': 1022, 'sea_level': 1022, 'temp': 21.54, 'temp_kf': 2.88, 'temp_max': 21.54, 'temp_min': 18.66}}
{'clouds': {'all': 8}, 'dt': 1726855200, 'dt_txt': '2024-09-20 18:00:00', 'main': {'feels_like': 20.82, 'grnd_level': 1011, 'humidity': 41, 'pressure': 1022, 'sea_level': 1022, 'temp': 21.54, 'temp_kf': 2.88, 'temp_max': 21.54, 'temp_min': 18.66}, 'pop': 0}
{'clouds': {'all': 8}, 'dt': 1726855200, 'dt_txt': '2024-09-20 18:00:00', 'main': {'feels_like': 20.82, 'grnd_level': 1011, 'humidity': 41, 'pressure': 1022, 'sea_level': 1022, 'temp': 21.54, 'temp_kf': 2.88, 'temp_max': 21.54, 'temp_min': 18.66}, 'pop': 0, 'sys': {'pod': 'n'}}
{'clouds': {'all': 8}, 'dt': 1726855200, 'dt_txt': '2024-09-20 18:00:00', 'ma

# convert this dictionary into a list of values


1. look above where i made the dictionary items add those to a list y
add ONLY the values

2. look above (or) below and add the values from the list to a z







In [48]:
g.keys()

dict_keys(['clouds', 'dt', 'dt_txt', 'main', 'pop', 'sys', 'visibility', 'weather', 'wind'])

In [49]:
# the goal is to get everything into a list




x=[]

for v in l.values():
  x.append(v)

x

[{'all': 8},
 1726855200,
 '2024-09-20 18:00:00',
 {'feels_like': 20.82,
  'grnd_level': 1011,
  'humidity': 41,
  'pressure': 1022,
  'sea_level': 1022,
  'temp': 21.54,
  'temp_kf': 2.88,
  'temp_max': 21.54,
  'temp_min': 18.66},
 0,
 {'pod': 'n'},
 10000,
 [{'description': 'чисте небо', 'icon': '01n', 'id': 800, 'main': 'Clear'}],
 {'deg': 11, 'gust': 2.96, 'speed': 2.91}]

In [50]:
w

[{'clouds': {'all': 8},
  'dt': 1726855200,
  'dt_txt': '2024-09-20 18:00:00',
  'main': {'feels_like': 20.82,
   'grnd_level': 1011,
   'humidity': 41,
   'pressure': 1022,
   'sea_level': 1022,
   'temp': 21.54,
   'temp_kf': 2.88,
   'temp_max': 21.54,
   'temp_min': 18.66},
  'pop': 0,
  'sys': {'pod': 'n'},
  'visibility': 10000,
  'weather': [{'description': 'чисте небо',
    'icon': '01n',
    'id': 800,
    'main': 'Clear'}],
  'wind': {'deg': 11, 'gust': 2.96, 'speed': 2.91}}]

In [51]:
g

{'clouds': {'all': 8},
 'dt': 1726855200,
 'dt_txt': '2024-09-20 18:00:00',
 'main': {'feels_like': 20.82,
  'grnd_level': 1011,
  'humidity': 41,
  'pressure': 1022,
  'sea_level': 1022,
  'temp': 21.54,
  'temp_kf': 2.88,
  'temp_max': 21.54,
  'temp_min': 18.66},
 'pop': 0,
 'sys': {'pod': 'n'},
 'visibility': 10000,
 'weather': [{'description': 'чисте небо',
   'icon': '01n',
   'id': 800,
   'main': 'Clear'}],
 'wind': {'deg': 11, 'gust': 2.96, 'speed': 2.91}}

In [52]:
isinstance(g,dict)


True


```

{'clouds': {'all': 8}, 'dt': 1726855200, 'dt_txt': '2024-09-20 18:00:00', 'main': {'feels_like': 20.82, 'grnd_level': 1011, 'humidity': 41, 'pressure': 1022, 'sea_level': 1022, 'temp': 21.54, 'temp_kf': 2.88, 'temp_max': 21.54, 'temp_min': 18.66}, 'pop': 0, 'sys': {'pod': 'n'}, 'visibility': 10000, 'weather': [{'description': 'чисте небо', 'icon': '01n', 'id': 800, 'main': 'Clear'}], 'wind': {'deg': 11, 'gust': 2.96, 'speed': 2.91}}

```

In [53]:
# this i is a variable created in loop over the list j['list'][0]['weather']

# weather data for 7 days

a=[]


#for i in j['list'][0]['weather']:



# this one has the answer already.  it looks at the whole j['list'][0]['weather'][0]

# and makes a dictionary of items ONLY WHEN IT's a LIST

d=j['list'][0]['weather'][0]

if isinstance(d,list):

  # make empty dictionary
  e=dict()

  # list all keys and values
  for k,v in d.items():
    # add the item with value v and key k
    e[k]=v
    print(e)

a.append(e)

a



[{'description': 'чисте небо', 'icon': '01n', 'id': 800, 'main': 'Clear'}]

In [54]:
s={}

s['name']="Maria"
s['countryy']='UK'

s

{'name': 'Maria', 'countryy': 'UK'}

In [55]:
d=j['list'][0]['weather']
d

[{'description': 'чисте небо', 'icon': '01n', 'id': 800, 'main': 'Clear'}]

# csv---command seperated values

date,temp,main,description
2024-09-20 18:00,18,cloudy,
